const CACHE='radar-caixa-brasil-pages-v6';
const BASE=new URL('./',self.location.href);const url=p=>new URL(p,BASE).toString();
const STATIC_ASSETS=[url('./'),url('index.html'),url('styles.css'),url('enhancements.css'),url('app-v4.js'),url('app-core.js'),url('manifest.webmanifest'),url('icons/icon-192.png'),url('icons/icon-512.png')];
const DATA_URL=url('data/imoveis-brasil.json'),DB_NAME='radar-caixa-brasil',STORE='settings';
self.addEventListener('install',e=>e.waitUntil(caches.open(CACHE).then(c=>c.addAll(STATIC_ASSETS)).then(()=>self.skipWaiting())));
self.addEventListener('activate',e=>e.waitUntil(Promise.all([caches.keys().then(keys=>Promise.all(keys.filter(k=>k!==CACHE).map(k=>caches.delete(k)))),self.clients.claim()])));
self.addEventListener('fetch',e=>{if(e.request.method!=='GET')return;e.respondWith(fetch(e.request).then(r=>{const clone=r.clone();caches.open(CACHE).then(c=>c.put(e.request,clone));return r}).catch(()=>caches.match(e.request).then(c=>c||caches.match(url('index.html')))))});
function openDb(){return new Promise((res,rej)=>{const q=indexedDB.open(DB_NAME,1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains(STORE))q.result.createObjectStore(STORE)};q.onsuccess=()=>res(q.result);q.onerror=()=>rej(q.error)})}
function dbGet(k,f){return openDb().then(db=>new Promise((res,rej)=>{const q=db.transaction(STORE,'readonly').objectStore(STORE).get(k);q.onsuccess=()=>res(q.result??f);q.onerror=()=>rej(q.error)}))}
function dbSet(k,v){return openDb().then(db=>new Promise((res,rej)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(v,k);tx.oncomplete=res;tx.onerror=()=>rej(tx.error)}))}
const norm=v=>String(v??'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase(),keyOf=p=>`${p.uf||''}:${p.numeroImovel||''}`;
function yes(v){const n=norm(v);return n.includes('sim')||n.includes('permit')||n.includes('aceit')}function no(v){return norm(v).includes('nao')}
function matches(p,f={}){if(f.state&&p.uf!==f.state||f.city&&p.cidade!==f.city||f.neighborhood&&p.bairro!==f.neighborhood||f.type&&p.tipoImovel!==f.type||f.modality&&p.modalidade!==f.modality)return false;for(const [fk,pk,op] of [['minPrice','preco','min'],['maxPrice','preco','max'],['minDiscount','desconto','min'],['bedrooms','quartos','min'],['bathrooms','banheiros','min'],['parking','vagas','min'],['minArea','areaPrivativa','min'],['maxArea','areaPrivativa','max']]){const l=Number(f[fk]||0);if(l>0&&(!Number.isFinite(p[pk])||(op==='min'?p[pk]<l:p[pk]>l)))return false}if(f.financing==='sim'&&!yes(p.financiamento)||f.financing==='nao'&&!no(p.financiamento))return false;return true}
async function check(){const r=await fetch(`${DATA_URL}?background=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const payload=await r.json(),props=Array.isArray(payload.properties)?payload.properties:[],ids=props.map(keyOf),known=await dbGet('knownIds',[]),profile=await dbGet('alertProfile',{});if(!known.length){await dbSet('knownIds',ids);return}const set=new Set(known),news=props.filter(p=>!set.has(keyOf(p))&&matches(p,profile));await dbSet('knownIds',ids);if(news.length)await self.registration.showNotification('Novos imóveis compatíveis na CAIXA',{body:`${news.length} nova${news.length===1?' oportunidade atende':'s oportunidades atendem'} ao seu alerta.`,icon:url('icons/icon-192.png'),badge:url('icons/icon-192.png'),tag:'radar-caixa-br-v6',renotify:true,data:{url:BASE.toString()}})}
self.addEventListener('periodicsync',e=>{if(e.tag==='check-properties')e.waitUntil(check())});self.addEventListener('sync',e=>{if(e.tag==='check-properties')e.waitUntil(check())});self.addEventListener('message',e=>{const d=e.data||{};if(d.type==='SYNC_CURRENT')e.waitUntil(Promise.all([dbSet('knownIds',Array.isArray(d.ids)?d.ids:[]),dbSet('alertProfile',d.alertProfile||{})]));if(d.type==='SET_ALERT_PROFILE')e.waitUntil(dbSet('alertProfile',d.alertProfile||{}));if(d.type==='CHECK_NOW')e.waitUntil(check())});self.addEventListener('notificationclick',e=>{e.notification.close();e.waitUntil((async()=>{const l=await clients.matchAll({type:'window',includeUncontrolled:true});for(const c of l)if('focus'in c)return c.focus();if(clients.openWindow)return clients.openWindow(e.notification.data?.url||BASE.toString())})())});
